config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :messages
  resources :departments
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/developer.rb
class Developer < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:dptname, :dptid)
    end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show edit update destroy ]

  # GET /developers or /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1 or /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers or /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save

        #Tell the DeveloperMailer to send a Wekcome Email after save
        DeveloperMailer.welcome_email(@developer).deviver
        
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully created." }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1 or /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully updated." }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1 or /developers/1.json
  def destroy
    @developer.destroy

    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Developer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def developer_params
      params.require(:developer).permit(:devname, :devid, :dptid, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title, :content, :dptidtosend, :msgid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Dptname:</strong>
    <%= department.dptname %>
  </p>

  <p>
    <strong>Dptid:</strong>
    <%= department.dptid %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <div class="field form-group">
    <%= form.text_field :dptname, class:'form-control', placeholder:'Enter Department Name' %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :dptid, class:'form-control', placeholder:'Enter Department ID' %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department, class:'btn btn-info' %>
  <%= link_to "Back to departments", departments_path, class:'btn btn-secondary' %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Department Informations</h1>


<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Department Name</th>
        <th>Department ID</th>
      </tr>
    </thead>

    <tbody>
      <% @departments.each do |department| %>
        <tr>
          <td>
            <%= link_to department.dptname , department %>
          </td>
          <td><%= department.dptid %></td>
          </tr>
      <% end %>
    </tbody>
</table>

<%= link_to "New department", new_department_path, class:'btn btn-primary' %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path, class:'btn btn-secondary' %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit", edit_department_path(@department), class:'btn btn-warning' %>
  <%= link_to "Back", departments_path, class:'btn btn-secondary' %>
  <br/><br/>
  <%= button_to "Delete", @department, method: :delete, class:'btn btn-danger' %>
</div>

app/views/developers/_developer.html.erb
<div id="<%= dom_id developer %>">
  <p>
    <strong>Devname:</strong>
    <%= developer.devname %>
  </p>

  <p>
    <strong>Devid:</strong>
    <%= developer.devid %>
  </p>

  <p>
    <strong>Dptid:</strong>
    <%= developer.dptid %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= developer.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= developer.phone %>
  </p>

</div>

app/views/developers/_form.html.erb
<%= form_with(model: developer) do |form| %>
  <% if developer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% developer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <div class ="field form-group">
    <%= form.text_field :devname, class:'form-control', placeholder:'Enter Developer Name' %>
  </div>
  <br/>
  <div class ="field form-group">
    <%= form.text_field :devid, class:'form-control', placeholder:'Enter Developer ID' %>
  </div>
  <br/>
  <div class ="field form-group">
    <%= form.text_field :dptid, class:'form-control', placeholder:'Enter Department ID' %>
  </div>
  <br/>
  <div class ="field form-group">
    <%= form.text_field :email, class:'form-control', placeholder:'Enter Mail' %>
  </div>
  <br/>
  <div class ="field form-group">
    <%= form.text_field :phone, class:'form-control', placeholder:'Enter Phone' %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Show this developer", @developer %> |
  <%= link_to "Back to developers", developers_path %>
</div>

app/views/developers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Developers</h1>


<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>ID</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Department</th>
      </tr>
    </thead>

    <tbody>
      <% @developers.each do |developer| %>
        <tr>
          <td>
            <%= link_to developer.devname , developer %>
          </td>
          <td><%= developer.devid %></td>
          <td><%= developer.phone %></td>
          <td><%= developer.email %></td>
          <td><%= developer.dptid %></td>
          </tr>
      <% end %>
    </tbody>
</table>

<%= link_to "New developer", new_developer_path, class:'btn btn-primary' %>

app/views/developers/new.html.erb
<h1>New developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Back to developers", developers_path, class:'btn btn-secondary' %>
</div>

app/views/developers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @developer %>

<div>
  <%= link_to "Edit", edit_developer_path(@developer), class:'btn btn-warning' %>
  <%= link_to "Back", developers_path, class:'btn btn-secondary' %>
  <br/><br/>
  <%= button_to "Destroy", @developer, method: :delete, class:'btn btn-danger' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Rails App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Departments', departments_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Team Messages', messages_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Developers', developers_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About Us </h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Notification Alert System</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Notification Alert System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = 'container'>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br/>
  
  <div class="field form-group">
    <%= form.text_field :title, class:'form-control', placeholder:'Provide Message Title' %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_area :content, class:'form-control', placeholder:'Write Message' %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :dptidtosend, class:'form-control', placeholder:'Provide Department ID to send Message' %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :msgid, class:'form-control', placeholder:'Message ID' %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Title ==> </strong>
    <%= message.title %>
  </p>

  <p>
    <strong>Content ==> </strong>
    <%= message.content %>
  </p>

  <p>
    <strong>Send to Department ==> </strong>
    <%= message.dptidtosend %>
  </p>

  <p>
    <strong>Message ID ==> </strong>
    <%= message.msgid %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message, class:'btn btn-info' %> 
  <%= link_to "Back to messages", messages_path, class:'btn btn-secondary' %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>


<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Department to Send</th>
        <th>Message ID</th>
      </tr>
    </thead>

    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td>
            <%= link_to message.title , message %>
          </td>
          <td><%= message.content %></td>
          <td>
            <%= link_to message.dptidtosend , departments_url %>
          </td>
          <td>
            <%= link_to message.msgid , message %>
          </td>
          </tr>
      <% end %>
    </tbody>
</table>

<%= link_to "New Message", new_message_path, class:'btn btn-primary' %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path, class:'btn btn-secondary' %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit", edit_message_path(@message), class:'btn btn-warning' %>
  <%= link_to "Back", messages_path, class:'btn btn-secondary' %>
  <br/><br/>
  <%= button_to "Destroy", @message, method: :delete, class:'btn btn-danger' %>
</div>